/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FlexBuild } from "./FlexBuild";
export * as factories from "./factories";
export { FlexBuild__factory } from "./factories/FlexBuild__factory";
